version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    tty: true
    environment:
      - SERVICE_NAME=app
      - SERVICE_TAGS=dev
    working_dir: /var/www/html
    volumes:
      - ../backend/:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=guesschar
      - MYSQL_ROOT_PASSWORD=root
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
